server.port=8888
spring.application.name=config-server

# Point vers votre dossier de configuration local
spring.cloud.config.server.native.search-locations=file:./config-repo
# OU si vous utilisez Git :
# spring.cloud.config.server.git.uri=https://github.com/votre-user/config-repo